server:
  port: 8887


spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.118.133:3306/xx_community


mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    root: info
  file:
    name: ~/log/xx_community.log
    max-size: 200MB
    max-history: 30


fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    max-total: 153
    max-wait-millis: 102
  tracker-list:
    - 192.168.118.133:22122
  web-server-url: http://192.168.118.133/


github:
  client:
    id: 0422b4182360f93e910a
    secret: d5ff10a423a34102e11b10425411f78bec36b939
  redirect:
    uri: http://localhost:8887/callback


remote:
  image:
    url: http://192.168.118.133:8888/images/